class Event(object):
    """
    A superclass for any events that might be generated by an
    object and sent to the EventManager.
    """
    
    def __init__(self):
        self.name = "Generic event"
    def __str__(self):
        return self.name